version: '2'
services:
  web:
    build: .
    image: garcianavalon/remote_interview
    depends_on:
      - mongo
    environment:
      - DEBUG=remote_interview:*
    volumes:
      - .:/app
    command: [nodemon, ./bin/www]
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    volumes:
      - ./db:/data/db

